git:
  depth: false
  clone: false
branches:
  only:
    - master
language: java
jdk: openjdk8
install: true
cache:
  directories:
    - "$HOME/.m2"

before_install:
  - echo 'github.com ssh-rsa $PUBLIC_KEY' >> ~/.ssh/known_hosts
  - ls -la
  - git clone "https://github.com/onsense/universal.git" ./universal
  - cd ./universal
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/onsense/universal.git" > /dev/null 2>&1
  - git fetch --force origin "$TRAVIS_BRANCH:remotes/origin/$TRAVIS_BRANCH"
  - git reset --hard "HEAD"
  - git checkout -q -B "$TRAVIS_BRANCH"
  - git config --global gc.auto 0 || true
  - git config user.name "$COMMIT_AUTHOR_NAME"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - ls -la
  - openssl version -a
  - export COMMIT_MESSAGE=`git log -1 --oneline`
  - openssl aes-256-cbc -k "$travis_key_password" -in deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 400 ./deploy_key
  - ssh-add ./deploy_key
  - git branch --set-upstream-to=origin/$TRAVIS_BRANCH $TRAVIS_BRANCH
  - git pull

script:
  - mvn clean install

deploy:
  provider: script
  script: chmod +x ./configure-maven.sh && ./configure-maven.sh && chmod -x ./configure-maven.sh
    && mvn --settings .mvn/conf/settings.xml --batch-mode --activate-profiles release
    --fail-at-end org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare
    -DskipTests=true -DskipITs=true -Darguments="-DskipTests=true -DskipITs=true"
  skip_cleanup: true
  on:
    all_branches: false

env:
  global:
    secure: bBUnstRlqD4snwiw8MbgO1uyYXlyNvgTk3RecbrOMcLTtKjCDk3RM2H7HOu602yGBdfSmESEv9/slL6eNWO87/GUbGfx8wqSimU5qhPpeFOG65GCfLZvkF3KC+NWh6hjwPerbxO7ZgQLCzhzzpvrh9JtrmajJsJ6aADUaqO94DZus8f279T1+dtPgUurMvCpzY7tAt9S3Jj4hUibN4Njy6bMVQ89UlgoB9VuJEhZeBgeZDApWz55HpVQLGhAF+53qZ0CTwuc96eq/vKOiJi7RBnc92iNgsUp91+Mv7xisZm+ST9asja0iaTmXMAGgd/lImzWXkD3QIjVPPeDIZVTr76nNTGI1LyJEd3Ov1oF9iPF3WRb/I7suiMSQm7evdqkpupqjZsobJKyERClUunbs01b7AEdX/Jp24ClBNYeLDaYbYxBxKW8TU8w+q5ytRjGKyFteuGtl415SkG6z2hFfXW7jOyb0BUM/y8Mdp07YqWexS5/vPuL1UQphL3fzpVyu6W+oNprJoSf7OxLfAMJZbAZkKTVXEZeLvdAjMZSNAHsuHfCpva26YsCtcG7poXjum/JChqqlhgbOarzkKD4xrjvYSwog2QgyEy2flra9e8AKIrc8ji1Kog/WJR3sebfSEgJyK/uNqIkKYIHBoi5TKbBnlH8Do8cqOhN6UsEuhQ=
