git:
  depth: false
  clone: false
branches:
  only:
    - master
language: java
jdk: openjdk8
install: true
cache:
  directories:
    - "$HOME/.m2"

before_install:
  - echo 'github.com ssh-rsa $PUBLIC_KEY' >> ~/.ssh/known_hosts
  - ls -la
  - git clone "https://github.com/onsense/universal.git" ./universal
  - cd ./universal
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/onsense/universal.git" > /dev/null 2>&1
  - git fetch --force origin "$TRAVIS_BRANCH:remotes/origin/$TRAVIS_BRANCH"
  - git reset --hard "HEAD"
  - git checkout -q -B "$TRAVIS_BRANCH"
  - git config --global gc.auto 0 || true
  - git config user.name "$COMMIT_AUTHOR_NAME"
  - git config user.email "$COMMIT_AUTHOR_EMAIL"
  - ls -la
  - openssl version -a
  - export COMMIT_MESSAGE=`git log -1 --oneline`
  - openssl aes-256-cbc -k "$travis_key_password" -in deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 400 ./deploy_key
  - ssh-add ./deploy_key
  - git branch --set-upstream-to=origin/$TRAVIS_BRANCH $TRAVIS_BRANCH
  - git pull

script:
  - mvn clean install

deploy:
  provider: script
  script: chmod +x ./configure-maven.sh && ./configure-maven.sh && chmod -x ./configure-maven.sh
    && mvn --settings .mvn/conf/settings.xml --batch-mode --activate-profiles release
    --fail-at-end org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare
    -DskipTests=true -DskipITs=true -Darguments="-DskipTests=true -DskipITs=true"
  skip_cleanup: true
  on:
    all_branches: false

env:
  global:
    - secure: O/63hfvRiqRm+y/yrE/3v4AzOieLx02pYENW2eDm8ykHpkonskgzfUEVli+CV9RqOCewXbsqba6loS+U47h8JF5JlC0hKOOjYBKWGWl6mNCn0Zd2cG1VKH3WGq8RbSHYvNRjMzaalQ+IPZX5cm9hcLq917aLKd/WpvMgiNSUsxU6zSysWC/0MrI6oJ0/y2dwKEGJ3vPmnK76jn22Q2nz2gYZmEyKw9BVfHtTE2gLu5Ze3mxUb65sNM4qjcH/n8pho3svZ820ou03TlmssmwB/z4QvzfRZFDOKx3S6En4RA/Daqd+4XpFb0uWBv2RfAY8Z5JZhmg1P2nfIU8kmidaEU6pHZOwRlHnb0GYUgg3w2Gc5vWd13dcJSyRV3S1VOpnPLyJVB5DIS5Hr3UKiCTyRQj7qKrk8C0gx5UZtJzUnfSVyuZJuRhl1wenXeg80C6Ixg0QJmayr1tSkz7lAF2DtVrmkc15v+nG9edZJJifjIiQDWNd4KD/nTECC2Ht3vcEFOcZ64ROe07U3F9AXSWTJLzhFjKXQyWaYwhp8ACX+z47dGZ/1G2g9tkXBr8opy9pK23OWgfcLkX8zkB5RcMgUUGdvbNg+sfgezANscOuEgjooshSgQLUrg9cmQtDFAQwhXO9/IZO4eVobXvL2YPy8AbHBDyYd181XTM5akFuN9U=
